<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        Country::truncate();
        Schema::enableForeignKeyConstraints();

        $countries = [
            [
                'flag' => 'afghanistan.png',
                'name' => 'Afghanistan',
                'alpha_two_code' => 'AF',
                'phone_code' => '+93',
            ],
            [
                'flag' => 'aland-islands.png',
                'name' => 'Åland Islands',
                'alpha_two_code' => 'AX',
                'phone_code' => '+358 18',
            ],
            [
                'flag' => 'albania.png',
                'name' => 'Albania',
                'alpha_two_code' => 'AL',
                'phone_code' => '+355',
            ],
            [
                'flag' => 'algeria.png',
                'name' => 'Algeria',
                'alpha_two_code' => 'DZ',
                'phone_code' => '+213',
            ],
            [
                'flag' => 'american-samoa.png',
                'name' => 'American Samoa',
                'alpha_two_code' => 'AS',
                'phone_code' => '+1 684',
            ],
            [
                'flag' => 'andorra.png',
                'name' => 'Andorra',
                'alpha_two_code' => 'AD',
                'phone_code' => '+376',
            ],
            [
                'flag' => 'angola.png',
                'name' => 'Angola',
                'alpha_two_code' => 'AO',
                'phone_code' => '+244',
            ],
            [
                'flag' => 'anguilla.png',
                'name' => 'Anguilla',
                'alpha_two_code' => 'AI',
                'phone_code' => '+1 264',
            ],
            [
                'flag' => 'antigua-and-barbuda.png',
                'name' => 'Antigua and Barbuda',
                'alpha_two_code' => 'AG',
                'phone_code' => '+1',
            ],
            [
                'flag' => 'argentina.png',
                'name' => 'Argentina',
                'alpha_two_code' => 'AR',
                'phone_code' => '+54',
            ],
            [
                'flag' => 'armenia.png',
                'name' => 'Armenia',
                'alpha_two_code' => 'AM',
                'phone_code' => '+374',
            ],
            [
                'flag' => 'aruba.png',
                'name' => 'Aruba',
                'alpha_two_code' => 'AW',
                'phone_code' => '+297',
            ],
            [
                'flag' => 'australia.png',
                'name' => 'australia',
                'alpha_two_code' => 'AU',
                'phone_code' => '+61',
            ],
            [
                'flag' => 'austria.png',
                'name' => 'Austria',
                'alpha_two_code' => 'AT',
                'phone_code' => '+43',
            ],
            [
                'flag' => 'azerbaijan.png',
                'name' => 'Azerbaijan',
                'alpha_two_code' => 'AZ',
                'phone_code' => '+994',
            ],
            [
                'flag' => 'bahamas.png',
                'name' => 'Bahamas',
                'alpha_two_code' => 'BS',
                'phone_code' => '+1 242',
            ],
            [
                'flag' => 'bahrain.png',
                'name' => 'Bahrain',
                'alpha_two_code' => 'BH',
                'phone_code' => '+973',
            ],
            [
                'flag' => 'bangladesh.png',
                'name' => 'Bangladesh',
                'alpha_two_code' => 'BD',
                'phone_code' => '+880',
            ],
            [
                'flag' => 'barbados.png',
                'name' => 'Barbados',
                'alpha_two_code' => 'BB',
                'phone_code' => '+1 246',
            ],
            [
                'flag' => 'belarus.png',
                'name' => 'Belarus',
                'alpha_two_code' => 'BY',
                'phone_code' => '+375',
            ],
            [
                'flag' => 'belgium.png',
                'name' => 'Belgium',
                'alpha_two_code' => 'BE',
                'phone_code' => '+32',
            ],
            [
                'flag' => 'belize.png',
                'name' => 'Belize',
                'alpha_two_code' => 'BZ',
                'phone_code' => '+501',
            ],
            [
                'flag' => 'benin.png',
                'name' => 'Benin',
                'alpha_two_code' => 'BJ',
                'phone_code' => '+229',
            ],
            [
                'flag' => 'bermuda.png',
                'name' => 'Bermuda',
                'alpha_two_code' => 'BM',
                'phone_code' => '+1 441',
            ],
            [
                'flag' => 'bhutan.png',
                'name' => 'Bhutan',
                'alpha_two_code' => 'BT',
                'phone_code' => '+975',
            ],
            [
                'flag' => 'bolivia.png',
                'name' => 'Bolivia',
                'alpha_two_code' => 'BO',
                'phone_code' => '+591',
            ],
            [
                'flag' => 'bonaire.png',
                'name' => 'Bonaire, Sint Eustatius and Saba',
                'alpha_two_code' => 'BQ',
                'phone_code' => '+599 7',
            ],
            [
                'flag' => 'bosnia-and-herzegovina.png',
                'name' => 'Bosnia and Herzegovina',
                'alpha_two_code' => 'BA',
                'phone_code' => '+387',
            ],
            [
                'flag' => 'botswana.png',
                'name' => 'Botswana',
                'alpha_two_code' => 'BW',
                'phone_code' => '+267',
            ],
            [
                'flag' => 'brazil.png',
                'name' => 'Brazil',
                'alpha_two_code' => 'BR',
                'phone_code' => '+55',
            ],
            [
                'flag' => 'british-indian-ocean-territory.png',
                'name' => 'British Indian Ocean Territory',
                'alpha_two_code' => 'IO',
                'phone_code' => '+246',
            ],
            [
                'flag' => 'british-virgin-islands.png',
                'name' => 'British Virgin Islands',
                'alpha_two_code' => 'VG',
                'phone_code' => '+1 284',
            ],
            [
                'flag' => 'brunei.png',
                'name' => 'Brunei Darussalam',
                'alpha_two_code' => 'BN',
                'phone_code' => '+673',
            ],
            [
                'flag' => 'bulgaria.png',
                'name' => 'Bulgaria',
                'alpha_two_code' => 'BG',
                'phone_code' => '+359',
            ],
            [
                'flag' => 'burkina-faso.png',
                'name' => 'Burkina Faso',
                'alpha_two_code' => 'BF',
                'phone_code' => '+226',
            ],
            [
                'flag' => 'burundi.png',
                'name' => 'Burundi',
                'alpha_two_code' => 'BI',
                'phone_code' => '+257',
            ],
            [
                'flag' => 'cambodia.png',
                'name' => 'Cambodia',
                'alpha_two_code' => 'KH',
                'phone_code' => '+855',
            ],
            [
                'flag' => 'cameroon.png',
                'name' => 'Cameroon',
                'alpha_two_code' => 'CM',
                'phone_code' => '+237',
            ],
            [
                'flag' => 'canada.png',
                'name' => 'Canada',
                'alpha_two_code' => 'CA',
                'phone_code' => '+1',
            ],
            [
                'flag' => 'cayman-islands.png',
                'name' => 'Cayman Islands',
                'alpha_two_code' => 'KY',
                'phone_code' => '+1 345',
            ],
            [
                'flag' => 'central-african-republic.png',
                'name' => 'Central African Republic',
                'alpha_two_code' => 'CF',
                'phone_code' => '+236',
            ],
            [
                'flag' => 'chad.png',
                'name' => 'Chad',
                'alpha_two_code' => 'TD',
                'phone_code' => '+235',
            ],
            [
                'flag' => 'chile.png',
                'name' => 'Chile',
                'alpha_two_code' => 'CL',
                'phone_code' => '+56',
            ],
            [
                'flag' => 'china.png',
                'name' => 'China',
                'alpha_two_code' => 'CN',
                'phone_code' => '+86',
            ],
            [
                'flag' => 'christmas-island.png',
                'name' => 'Christmas Island',
                'alpha_two_code' => 'CX',
                'phone_code' => '+61 89164',
            ],
            [
                'flag' => 'cocos-island.png',
                'name' => 'Cocos (Keeling) Islands',
                'alpha_two_code' => 'CC',
                'phone_code' => '+61 89162',
            ],
            [
                'flag' => 'colombia.png',
                'name' => 'Colombia',
                'alpha_two_code' => 'CO',
                'phone_code' => '+57',
            ],
            [
                'flag' => 'comoros.png',
                'name' => 'Comoros',
                'alpha_two_code' => 'KM',
                'phone_code' => '+269',
            ],
            [
                'flag' => 'democratic-republic-of-congo.png',
                'name' => 'Congo, (Democratic Republic)',
                'alpha_two_code' => 'CD',
                'phone_code' => '+243',
            ],
            [
                'flag' => 'cook-islands.png',
                'name' => 'Cook Islands',
                'alpha_two_code' => 'CK',
                'phone_code' => '+682',
            ],
            [
                'flag' => 'costa-rica.png',
                'name' => 'Costa Rica',
                'alpha_two_code' => 'CR',
                'phone_code' => '+506',
            ],
            [
                'flag' => 'croatia.png',
                'name' => 'Croatia',
                'alpha_two_code' => 'HR',
                'phone_code' => '+385',
            ],
            [
                'flag' => 'cuba.png',
                'name' => 'Cuba',
                'alpha_two_code' => 'CU',
                'phone_code' => '+53',
            ],
            [
                'flag' => 'curacao.png',
                'name' => 'Curaçao',
                'alpha_two_code' => 'CW',
                'phone_code' => '+599 9',
            ],
            [
                'flag' => 'cyprus.png',
                'name' => 'Cyprus',
                'alpha_two_code' => 'CY',
                'phone_code' => '+357',
            ],
            [
                'flag' => 'czech-republic.png',
                'name' => 'Czech Republic',
                'alpha_two_code' => 'CZ',
                'phone_code' => '+420',
            ],
            [
                'flag' => 'denmark.png',
                'name' => 'Denmark',
                'alpha_two_code' => 'DK',
                'phone_code' => '+45',
            ],
            [
                'flag' => 'djibouti.png',
                'name' => 'Djibouti',
                'alpha_two_code' => 'DJ',
                'phone_code' => '+253',
            ],
            [
                'flag' => 'dominica.png',
                'name' => 'Dominica',
                'alpha_two_code' => 'DM',
                'phone_code' => '+1 767',
            ],
            [
                'flag' => 'dominican-republic.png',
                'name' => 'Dominican Republic',
                'alpha_two_code' => 'DO',
                'phone_code' => '+1 809',
            ],
            [
                'flag' => 'ecuador.png',
                'name' => 'Ecuador',
                'alpha_two_code' => 'EC',
                'phone_code' => '+593',
            ],
            [
                'flag' => 'egypt.png',
                'name' => 'Egypt',
                'alpha_two_code' => 'EG',
                'phone_code' => '+20',
            ],
            [
                'flag' => 'el-salvador.png',
                'name' => 'El Salvador',
                'alpha_two_code' => 'SV',
                'phone_code' => '+503',
            ],
            [
                'flag' => 'equatorial-guinea.png',
                'name' => 'Equatorial Guinea',
                'alpha_two_code' => 'GQ',
                'phone_code' => '+240',
            ],
            [
                'flag' => 'eritrea.png',
                'name' => 'Eritrea',
                'alpha_two_code' => 'ER',
                'phone_code' => '+291',
            ],
            [
                'flag' => 'estonia.png',
                'name' => 'Estonia',
                'alpha_two_code' => 'EE',
                'phone_code' => '+372',
            ],
            [
                'flag' => 'ethiopia.png',
                'name' => 'Ethiopia',
                'alpha_two_code' => 'ET',
                'phone_code' => '+251',
            ],
            [
                'flag' => 'falkland-islands.png',
                'name' => 'Falkland Islands (Malvinas)',
                'alpha_two_code' => 'FK',
                'phone_code' => '+500',
            ],
            [
                'flag' => 'faroe-islands.png',
                'name' => 'Faroe Islands',
                'alpha_two_code' => 'FO',
                'phone_code' => '+298',
            ],
            [
                'flag' => 'fiji.png',
                'name' => 'Fiji',
                'alpha_two_code' => 'FJ',
                'phone_code' => '+679',
            ],
            [
                'flag' => 'finland.png',
                'name' => 'Finland',
                'alpha_two_code' => 'FI',
                'phone_code' => '+358',
            ],
            [
                'flag' => 'france.png',
                'name' => 'France',
                'alpha_two_code' => 'FR',
                'phone_code' => '+33',
            ],
            [
                'flag' => 'french-guiana.png',
                'name' => 'French Guiana',
                'alpha_two_code' => 'GF',
                'phone_code' => '+594',
            ],
            [
                'flag' => 'french-polynesia.png',
                'name' => 'French Polynesia',
                'alpha_two_code' => 'PF',
                'phone_code' => '+689',
            ],
            [
                'flag' => 'gabon.png',
                'name' => 'Gabon',
                'alpha_two_code' => 'GA',
                'phone_code' => '+241',
            ],
            [
                'flag' => 'gambia.png',
                'name' => 'Gambia',
                'alpha_two_code' => 'GM',
                'phone_code' => '+220',
            ],
            [
                'flag' => 'georgia.png',
                'name' => 'Georgia',
                'alpha_two_code' => 'GE',
                'phone_code' => '+995',
            ],
            [
                'flag' => 'germany.png',
                'name' => 'Germany',
                'alpha_two_code' => 'DE',
                'phone_code' => '+49',
            ],
            [
                'flag' => 'ghana.png',
                'name' => 'Ghana',
                'alpha_two_code' => 'GH',
                'phone_code' => '+233',
            ],
            [
                'flag' => 'gibraltar.png',
                'name' => 'Gibraltar',
                'alpha_two_code' => 'GI',
                'phone_code' => '+350',
            ],
            [
                'flag' => 'greece.png',
                'name' => 'Greece',
                'alpha_two_code' => 'GR',
                'phone_code' => '+30',
            ],
            [
                'flag' => 'greenland.png',
                'name' => 'Greenland',
                'alpha_two_code' => 'GL',
                'phone_code' => '+299',
            ],
            [
                'flag' => 'grenada.png',
                'name' => 'Grenada',
                'alpha_two_code' => 'GD',
                'phone_code' => '+1 473',
            ],
            [
                'flag' => 'guadeloupe.png',
                'name' => 'Guadeloupe',
                'alpha_two_code' => 'GP',
                'phone_code' => '+590',
            ],
            [
                'flag' => 'guam.png',
                'name' => 'Guam',
                'alpha_two_code' => 'GU',
                'phone_code' => '+1 671',
            ],
            [
                'flag' => 'guatemala.png',
                'name' => 'Guatemala',
                'alpha_two_code' => 'GT',
                'phone_code' => '+502',
            ],
            [
                'flag' => 'guernsey.png',
                'name' => 'Guernsey',
                'alpha_two_code' => 'GG',
                'phone_code' => '+44 1481',
            ],
            [
                'flag' => 'guinea.png',
                'name' => 'Guinea',
                'alpha_two_code' => 'GN',
                'phone_code' => '+224',
            ],
            [
                'flag' => 'guinea-bissau.png',
                'name' => 'Guinea-Bissau',
                'alpha_two_code' => 'GW',
                'phone_code' => '+245',
            ],
            [
                'flag' => 'guyana.png',
                'name' => 'Guyana',
                'alpha_two_code' => 'GY',
                'phone_code' => '+592',
            ],
            [
                'flag' => 'haiti.png',
                'name' => 'Haiti',
                'alpha_two_code' => 'HT',
                'phone_code' => '+509',
            ],
            [
                'flag' => 'honduras.png',
                'name' => 'Honduras',
                'alpha_two_code' => 'HN',
                'phone_code' => '+504',
            ],
            [
                'flag' => 'hong-kong.png',
                'name' => 'Hong Kong',
                'alpha_two_code' => 'HK',
                'phone_code' => '+852',
            ],
            [
                'flag' => 'hungary.png',
                'name' => 'Hungary',
                'alpha_two_code' => 'HU',
                'phone_code' => '+36',
            ],
            [
                'flag' => 'iceland.png',
                'name' => 'Iceland',
                'alpha_two_code' => 'IS',
                'phone_code' => '+354',
            ],
            [
                'flag' => 'india.png',
                'name' => 'India',
                'alpha_two_code' => 'IN',
                'phone_code' => '+91',
            ],
            [
                'flag' => 'indonesia.png',
                'name' => 'Indonesia',
                'alpha_two_code' => 'ID',
                'phone_code' => '+62',
            ],
            [
                'flag' => 'iran.png',
                'name' => 'Iran, Islamic Republic',
                'alpha_two_code' => 'IR',
                'phone_code' => '+98',
            ],
            [
                'flag' => 'iraq.png',
                'name' => 'Iraq',
                'alpha_two_code' => 'IQ',
                'phone_code' => '+964',
            ],
            [
                'flag' => 'ireland.png',
                'name' => 'Ireland',
                'alpha_two_code' => 'IE',
                'phone_code' => '+353',
            ],
            [
                'flag' => 'isle-of-man.png',
                'name' => 'Isle of Man',
                'alpha_two_code' => 'IM',
                'phone_code' => '+44 1624',
            ],
            [
                'flag' => 'israel.png',
                'name' => 'Israel',
                'alpha_two_code' => 'IL',
                'phone_code' => '+972',
            ],
            [
                'flag' => 'italy.png',
                'name' => 'Italy',
                'alpha_two_code' => 'IT',
                'phone_code' => '+39',
            ],
            [
                'flag' => 'jamaica.png',
                'name' => 'Jamaica',
                'alpha_two_code' => 'JM',
                'phone_code' => '+1 658',
            ],
            [
                'flag' => 'japan.png',
                'name' => 'Japan',
                'alpha_two_code' => 'JP',
                'phone_code' => '+81',
            ],
            [
                'flag' => 'jersey.png',
                'name' => 'Jersey',
                'alpha_two_code' => 'JE',
                'phone_code' => '+44 1534',
            ],
            [
                'flag' => 'jordan.png',
                'name' => 'Jordan',
                'alpha_two_code' => 'JO',
                'phone_code' => '+962',
            ],
            [
                'flag' => 'kazakhstan.png',
                'name' => 'Kazakhstan',
                'alpha_two_code' => 'KZ',
                'phone_code' => '+7 6',
            ],
            [
                'flag' => 'kenya.png',
                'name' => 'Kenya',
                'alpha_two_code' => 'KE',
                'phone_code' => '+254',
            ],
            [
                'flag' => 'kiribati.png',
                'name' => 'Kiribati',
                'alpha_two_code' => 'KI',
                'phone_code' => '+686',
            ],
            [
                'flag' => 'north-korea.png',
                'name' => "Korea, Democratic People's Republic",
                'alpha_two_code' => 'KP',
                'phone_code' => '+850',
            ],
            [
                'flag' => 'south-korea.png',
                'name' => 'Korea, Republic of Korea',
                'alpha_two_code' => 'KR',
                'phone_code' => '+82',
            ],
            [
                'flag' => 'kuwait.png',
                'name' => 'Kuwait',
                'alpha_two_code' => 'KW',
                'phone_code' => '+965',
            ],
            [
                'flag' => 'kyrgyzstan.png',
                'name' => 'Kyrgyzstan',
                'alpha_two_code' => 'KG',
                'phone_code' => '+996',
            ],
            [
                'flag' => 'laos.png',
                'name' => "Lao People's Democratic Republic",
                'alpha_two_code' => 'LA',
                'phone_code' => '+856',
            ],
            [
                'flag' => 'latvia.png',
                'name' => 'Latvia',
                'alpha_two_code' => 'LV',
                'phone_code' => '+371',
            ],
            [
                'flag' => 'lebanon.png',
                'name' => 'Lebanon',
                'alpha_two_code' => 'LB',
                'phone_code' => '+961',
            ],
            [
                'flag' => 'lesotho.png',
                'name' => 'Lesotho',
                'alpha_two_code' => 'LS',
                'phone_code' => '+266',
            ],
            [
                'flag' => 'liberia.png',
                'name' => 'Liberia',
                'alpha_two_code' => 'LR',
                'phone_code' => '+231',
            ],
            [
                'flag' => 'libya.png',
                'name' => 'Libya',
                'alpha_two_code' => 'LY',
                'phone_code' => '+218',
            ],
            [
                'flag' => 'liechtenstein.png',
                'name' => 'Liechtenstein',
                'alpha_two_code' => 'LI',
                'phone_code' => '+423',
            ],
            [
                'flag' => 'lithuania.png',
                'name' => 'Lithuania',
                'alpha_two_code' => 'LT',
                'phone_code' => '+370',
            ],
            [
                'flag' => 'luxembourg.png',
                'name' => 'Luxembourg',
                'alpha_two_code' => 'LU',
                'phone_code' => '+352',
            ],
            [
                'flag' => 'macao.png',
                'name' => 'Macao',
                'alpha_two_code' => 'MO',
                'phone_code' => '+853',
            ],
            [
                'flag' => 'north-macedonia.png',
                'name' => 'North Macedonia',
                'alpha_two_code' => 'MK',
                'phone_code' => '+389',
            ],
            [
                'flag' => 'madagascar.png',
                'name' => 'Madagascar',
                'alpha_two_code' => 'MG',
                'phone_code' => '+261',
            ],
            [
                'flag' => 'malawi.png',
                'name' => 'Malawi',
                'alpha_two_code' => 'MW',
                'phone_code' => '+265',
            ],
            [
                'flag' => 'malaysia.png',
                'name' => 'Malaysia',
                'alpha_two_code' => 'MY',
                'phone_code' => '+60',
            ],
            [
                'flag' => 'maldives.png',
                'name' => 'Maldives',
                'alpha_two_code' => 'MV',
                'phone_code' => '+960',
            ],
            [
                'flag' => 'mali.png',
                'name' => 'Mali',
                'alpha_two_code' => 'ML',
                'phone_code' => '+223',
            ],
            [
                'flag' => 'malta.png',
                'name' => 'Malta',
                'alpha_two_code' => 'MT',
                'phone_code' => '+356',
            ],
            [
                'flag' => 'marshall-islands.png',
                'name' => 'Marshall Islands',
                'alpha_two_code' => 'MH',
                'phone_code' => '+692',
            ],
            [
                'flag' => 'martinique.png',
                'name' => 'Martinique',
                'alpha_two_code' => 'MQ',
                'phone_code' => '+596',
            ],
            [
                'flag' => 'mauritania.png',
                'name' => 'Mauritania',
                'alpha_two_code' => 'MR',
                'phone_code' => '+222',
            ],
            [
                'flag' => 'mauritius.png',
                'name' => 'Mauritius',
                'alpha_two_code' => 'MU',
                'phone_code' => '+230',
            ],
            [
                'flag' => 'mayotte.png',
                'name' => 'Mayotte',
                'alpha_two_code' => 'YT',
                'phone_code' => '+262 269',
            ],
            [
                'flag' => 'mexico.png',
                'name' => 'Mexico',
                'alpha_two_code' => 'MX',
                'phone_code' => '+52',
            ],
            [
                'flag' => 'micronesia.png',
                'name' => 'Micronesia, Federated States',
                'alpha_two_code' => 'FM',
                'phone_code' => '+691',
            ],
            [
                'flag' => 'moldova.png',
                'name' => 'Moldova, Republic',
                'alpha_two_code' => 'MD',
                'phone_code' => '+373',
            ],
            [
                'flag' => 'monaco.png',
                'name' => 'Monaco',
                'alpha_two_code' => 'MC',
                'phone_code' => '+377',
            ],
            [
                'flag' => 'mongolia.png',
                'name' => 'Mongolia',
                'alpha_two_code' => 'MN',
                'phone_code' => '+976',
            ],
            [
                'flag' => 'montenegro.png',
                'name' => 'Montenegro',
                'alpha_two_code' => 'ME',
                'phone_code' => '+382',
            ],
            [
                'flag' => 'montserrat.png',
                'name' => 'Montserrat',
                'alpha_two_code' => 'MS',
                'phone_code' => '+1 664',
            ],
            [
                'flag' => 'morocco.png',
                'name' => 'Morocco',
                'alpha_two_code' => 'MA',
                'phone_code' => '+212',
            ],
            [
                'flag' => 'mozambique.png',
                'name' => 'Mozambique',
                'alpha_two_code' => 'MZ',
                'phone_code' => '+258',
            ],
            [
                'flag' => 'myanmar.png',
                'name' => 'Myanmar',
                'alpha_two_code' => 'MM',
                'phone_code' => '+95',
            ],
            [
                'flag' => 'namibia.png',
                'name' => 'Namibia',
                'alpha_two_code' => 'NA',
                'phone_code' => '+264',
            ],
            [
                'flag' => 'nauru.png',
                'name' => 'Nauru',
                'alpha_two_code' => 'NR',
                'phone_code' => '+674',
            ],
            [
                'flag' => 'nepal.png',
                'name' => 'Nepal',
                'alpha_two_code' => 'NP',
                'phone_code' => '+977',
            ],
            [
                'flag' => 'netherlands.png',
                'name' => 'Netherlands',
                'alpha_two_code' => 'NL',
                'phone_code' => '+31',
            ],
            [
                'flag' => 'new-caledonia.png',
                'name' => 'New Caledonia',
                'alpha_two_code' => 'NC',
                'phone_code' => '+687',
            ],
            [
                'flag' => 'new-zealand.png',
                'name' => 'New Zealand',
                'alpha_two_code' => 'NZ',
                'phone_code' => '+64',
            ],
            [
                'flag' => 'nicaragua.png',
                'name' => 'Nicaragua',
                'alpha_two_code' => 'NI',
                'phone_code' => '+505',
            ],
            [
                'flag' => 'niger.png',
                'name' => 'Niger',
                'alpha_two_code' => 'NE',
                'phone_code' => '+227',
            ],
            [
                'flag' => 'nigeria.png',
                'name' => 'Nigeria',
                'alpha_two_code' => 'NG',
                'phone_code' => '+234',
            ],
            [
                'flag' => 'niue.png',
                'name' => 'Niue',
                'alpha_two_code' => 'NU',
                'phone_code' => '+683',
            ],
            [
                'flag' => 'norfolk-island.png',
                'name' => 'Norfolk Island',
                'alpha_two_code' => 'NF',
                'phone_code' => '+672 3',
            ],
            [
                'flag' => 'northern-mariana-islands.png',
                'name' => 'Northern Mariana Islands',
                'alpha_two_code' => 'MP',
                'phone_code' => '+1 670',
            ],
            [
                'flag' => 'norway.png',
                'name' => 'Norway',
                'alpha_two_code' => 'NO',
                'phone_code' => '+47',
            ],
            [
                'flag' => 'oman.png',
                'name' => 'Oman',
                'alpha_two_code' => 'OM',
                'phone_code' => '+968',
            ],
            [
                'flag' => 'pakistan.png',
                'name' => 'Pakistan',
                'alpha_two_code' => 'PK',
                'phone_code' => '+92',
            ],
            [
                'flag' => 'palau.png',
                'name' => 'Palau',
                'alpha_two_code' => 'PW',
                'phone_code' => '+680',
            ],
            [
                'flag' => 'palestine.png',
                'name' => 'Palestine',
                'alpha_two_code' => 'PS',
                'phone_code' => '+970',
            ],
            [
                'flag' => 'panama.png',
                'name' => 'Panama',
                'alpha_two_code' => 'PA',
                'phone_code' => '+507',
            ],
            [
                'flag' => 'papua-new-guinea.png',
                'name' => 'Papua New Guinea',
                'alpha_two_code' => 'PG',
                'phone_code' => '+675',
            ],
            [
                'flag' => 'paraguay.png',
                'name' => 'Paraguay',
                'alpha_two_code' => 'PY',
                'phone_code' => '+595',
            ],
            [
                'flag' => 'peru.png',
                'name' => 'Peru',
                'alpha_two_code' => 'PE',
                'phone_code' => '+51',
            ],
            [
                'flag' => 'philippines.png',
                'name' => 'Philippines',
                'alpha_two_code' => 'PH',
                'phone_code' => '+63',
            ],
            [
                'flag' => 'pitcairn.png',
                'name' => 'Pitcairn Islands',
                'alpha_two_code' => 'PN',
                'phone_code' => '+64',
            ],
            [
                'flag' => 'poland.png',
                'name' => 'Poland',
                'alpha_two_code' => 'PL',
                'phone_code' => '+48',
            ],
            [
                'flag' => 'portugal.png',
                'name' => 'Portugal',
                'alpha_two_code' => 'PT',
                'phone_code' => '+351',
            ],
            [
                'flag' => 'puerto-rico.png',
                'name' => 'Puerto Rico',
                'alpha_two_code' => 'PR',
                'phone_code' => '+1 787',
            ],
            [
                'flag' => 'qatar.png',
                'name' => 'Qatar',
                'alpha_two_code' => 'QA',
                'phone_code' => '+974',
            ],
            [
                'flag' => 'reunion.png',
                'name' => 'Réunion',
                'alpha_two_code' => 'RE',
                'phone_code' => '+262',
            ],
            [
                'flag' => 'romania.png',
                'name' => 'Romania',
                'alpha_two_code' => 'RO',
                'phone_code' => '+40',
            ],
            [
                'flag' => 'russian-federation.png',
                'name' => 'Russian Federation',
                'alpha_two_code' => 'RU',
                'phone_code' => '+7',
            ],
            [
                'flag' => 'rwanda.png',
                'name' => 'Rwanda',
                'alpha_two_code' => 'RW',
                'phone_code' => '+250',
            ],
            [
                'flag' => 'saint-barthelemy.png',
                'name' => 'Saint Barthélemy',
                'alpha_two_code' => 'BL',
                'phone_code' => '+590',
            ],
            [
                'flag' => 'saint-helena.png',
                'name' => 'Saint Helena, Ascension and Tristan da Cunha',
                'alpha_two_code' => 'SH',
                'phone_code' => '+290',
            ],
            [
                'flag' => 'saint-kitts-and-nevis.png',
                'name' => 'Saint Kitts and Nevis',
                'alpha_two_code' => 'KN',
                'phone_code' => '+1 869',
            ],
            [
                'flag' => 'saint-lucia.png',
                'name' => 'Saint Lucia',
                'alpha_two_code' => 'LC',
                'phone_code' => '+1 758',
            ],
            [
                'flag' => 'saint-martin-french.png',
                'name' => 'Saint Martin (French part)',
                'alpha_two_code' => 'MF',
                'phone_code' => '+590',
            ],
            [
                'flag' => 'saint-pierre-and-miquelon.png',
                'name' => 'Saint Pierre and Miquelon',
                'alpha_two_code' => 'PM',
                'phone_code' => '+508',
            ],
            [
                'flag' => 'saint-vincent-and-grenadines.png',
                'name' => 'Saint Vincent and the Grenadines',
                'alpha_two_code' => 'VC',
                'phone_code' => '+1 784',
            ],
            [
                'flag' => 'samoa.png',
                'name' => 'Samoa',
                'alpha_two_code' => 'WS',
                'phone_code' => '+685',
            ],
            [
                'flag' => 'san-marino.png',
                'name' => 'San Marino',
                'alpha_two_code' => 'SM',
                'phone_code' => '+378',
            ],
            [
                'flag' => 'sao-tome-and-principe.png',
                'name' => 'Sao Tome and Principe',
                'alpha_two_code' => 'ST',
                'phone_code' => '+239',
            ],
            [
                'flag' => 'saudi-arabia.png',
                'name' => 'Saudi Arabia',
                'alpha_two_code' => 'SA',
                'phone_code' => '+966',
            ],
            [
                'flag' => 'senegal.png',
                'name' => 'Senegal',
                'alpha_two_code' => 'SN',
                'phone_code' => '+221',
            ],
            [
                'flag' => 'serbia.png',
                'name' => 'Serbia',
                'alpha_two_code' => 'RS',
                'phone_code' => '+381',
            ],
            [
                'flag' => 'seychelles.png',
                'name' => 'Seychelles',
                'alpha_two_code' => 'SC',
                'phone_code' => '+248',
            ],
            [
                'flag' => 'sierra-leone.png',
                'name' => 'Sierra Leone',
                'alpha_two_code' => 'SL',
                'phone_code' => '+232',
            ],
            [
                'flag' => 'singapore.png',
                'name' => 'Singapore',
                'alpha_two_code' => 'SG',
                'phone_code' => '+65',
            ],
            [
                'flag' => 'sint-maarten.png',
                'name' => 'Sint Maarten (Dutch part)',
                'alpha_two_code' => 'SX',
                'phone_code' => '+599 3',
            ],
            [
                'flag' => 'slovakia.png',
                'name' => 'Slovakia',
                'alpha_two_code' => 'SK',
                'phone_code' => '+421',
            ],
            [
                'flag' => 'slovenia.png',
                'name' => 'Slovenia',
                'alpha_two_code' => 'SI',
                'phone_code' => '+386',
            ],
            [
                'flag' => 'solomon-islands.png',
                'name' => 'Solomon Islands',
                'alpha_two_code' => 'SB',
                'phone_code' => '+677',
            ],
            [
                'flag' => 'somalia.png',
                'name' => 'Somalia',
                'alpha_two_code' => 'SO',
                'phone_code' => '+252',
            ],
            [
                'flag' => 'south-africa.png',
                'name' => 'South Africa',
                'alpha_two_code' => 'ZA',
                'phone_code' => '+27',
            ],
            [
                'flag' => 'south-georgia.png',
                'name' => 'South Georgia and the South Sandwich Islands',
                'alpha_two_code' => 'GS',
                'phone_code' => '+500',
            ],
            [
                'flag' => 'south-sudan.png',
                'name' => 'South Sudan',
                'alpha_two_code' => 'SS',
                'phone_code' => '+211',
            ],
            [
                'flag' => 'spain.png',
                'name' => 'Spain',
                'alpha_two_code' => 'ES',
                'phone_code' => '+34',
            ],
            [
                'flag' => 'sri-lanka.png',
                'name' => 'Sri Lanka',
                'alpha_two_code' => 'LK',
                'phone_code' => '+94',
            ],
            [
                'flag' => 'sudan.png',
                'name' => 'Sudan',
                'alpha_two_code' => 'SD',
                'phone_code' => '+249',
            ],
            [
                'flag' => 'suriname.png',
                'name' => 'Suriname',
                'alpha_two_code' => 'SR',
                'phone_code' => '+597',
            ],
            [
                'flag' => 'svalbard.png',
                'name' => 'Svalbard and Jan Mayen',
                'alpha_two_code' => 'SJ',
                'phone_code' => '+47 79',
            ],
            [
                'flag' => 'sweden.png',
                'name' => 'Sweden',
                'alpha_two_code' => 'SE',
                'phone_code' => '+46',
            ],
            [
                'flag' => 'switzerland.png',
                'name' => 'Switzerland',
                'alpha_two_code' => 'CH',
                'phone_code' => '+41',
            ],
            [
                'flag' => 'syria.png',
                'name' => 'Syrian Arab Republic',
                'alpha_two_code' => 'SY',
                'phone_code' => '+963',
            ],
            [
                'flag' => 'taiwan.png',
                'name' => 'Taiwan',
                'alpha_two_code' => 'TW',
                'phone_code' => '+886',
            ],
            [
                'flag' => 'tajikistan.png',
                'name' => 'Tajikistan',
                'alpha_two_code' => 'TJ',
                'phone_code' => '+992',
            ],
            [
                'flag' => 'tanzania.png',
                'name' => 'Tanzania, United Republic',
                'alpha_two_code' => 'TZ',
                'phone_code' => '+255',
            ],
            [
                'flag' => 'thailand.png',
                'name' => 'Thailand',
                'alpha_two_code' => 'TH',
                'phone_code' => '+66',
            ],
            [
                'flag' => 'timor-leste.png',
                'name' => 'Timor-Leste',
                'alpha_two_code' => 'TL',
                'phone_code' => 'TLS',
            ],
            [
                'flag' => 'togo.png',
                'name' => 'Togo',
                'alpha_two_code' => 'TG',
                'phone_code' => '+228',
            ],
            [
                'flag' => 'tokelau.png',
                'name' => 'Tokelau',
                'alpha_two_code' => 'TK',
                'phone_code' => '+690',
            ],
            [
                'flag' => 'tonga.png',
                'name' => 'Tonga',
                'alpha_two_code' => 'TO',
                'phone_code' => '+676',
            ],
            [
                'flag' => 'trinidad-and-tobago.png',
                'name' => 'Trinidad and Tobago',
                'alpha_two_code' => 'TT',
                'phone_code' => '+1 868',
            ],
            [
                'flag' => 'tunisia.png',
                'name' => 'Tunisia',
                'alpha_two_code' => 'TN',
                'phone_code' => '+216',
            ],
            [
                'flag' => 'turkey.png',
                'name' => 'Turkey',
                'alpha_two_code' => 'TR',
                'phone_code' => '+90',
            ],
            [
                'flag' => 'turkmenistan.png',
                'name' => 'Turkmenistan',
                'alpha_two_code' => 'TM',
                'phone_code' => '+993',
            ],
            [
                'flag' => 'turks-and-caicos-islands.png',
                'name' => 'Turks and Caicos Islands',
                'alpha_two_code' => 'TC',
                'phone_code' => '+1 649',
            ],
            [
                'flag' => 'tuvalu.png',
                'name' => 'Tuvalu',
                'alpha_two_code' => 'TV',
                'phone_code' => '+688',
            ],
            [
                'flag' => 'uganda.png',
                'name' => 'Uganda',
                'alpha_two_code' => 'UG',
                'phone_code' => '+256',
            ],
            [
                'flag' => 'ukraine.png',
                'name' => 'Ukraine',
                'alpha_two_code' => 'UA',
                'phone_code' => '+380',
            ],
            [
                'flag' => 'united-arab-emirates.png',
                'name' => 'United Arab Emirates',
                'alpha_two_code' => 'AE',
                'phone_code' => '+971',
            ],
            [
                'flag' => 'united-kingdom.png',
                'name' => 'United Kingdom',
                'alpha_two_code' => 'GB',
                'phone_code' => '+44',
            ],
            [
                'flag' => 'united-states.png',
                'name' => 'United States',
                'alpha_two_code' => 'US',
                'phone_code' => '+1',
            ],
            [
                'flag' => 'uruguay.png',
                'name' => 'Uruguay',
                'alpha_two_code' => 'UY',
                'phone_code' => '+598',
            ],
            [
                'flag' => 'uzbekistan.png',
                'name' => 'Uzbekistan',
                'alpha_two_code' => 'UZ',
                'phone_code' => '+998',
            ],
            [
                'flag' => 'vanuatu.png',
                'name' => 'Vanuatu',
                'alpha_two_code' => 'VU',
                'phone_code' => '+679',
            ],
            [
                'flag' => 'venezuela.png',
                'name' => 'Venezuela, Bolivarian Republic',
                'alpha_two_code' => 'VE',
                'phone_code' => '+58',
            ],
            [
                'flag' => 'vietnam.png',
                'name' => 'Viet Nam',
                'alpha_two_code' => 'VN',
                'phone_code' => '+84',
            ],
            [
                'flag' => 'virgin-islands.png',
                'name' => 'Virgin Islands, U.S.',
                'alpha_two_code' => 'VI',
                'phone_code' => '+1 340',
            ],
            [
                'flag' => 'wallis-and-futuna.png',
                'name' => 'Wallis and Futuna',
                'alpha_two_code' => 'WF',
                'phone_code' => '+681',
            ],
            [
                'flag' => 'yemen.png',
                'name' => 'Yemen',
                'alpha_two_code' => 'YE',
                'phone_code' => '+967',
            ],
            [
                'flag' => 'zambia.png',
                'name' => 'Zambia',
                'alpha_two_code' => 'ZM',
                'phone_code' => '+260',
            ],
            [
                'flag' => 'zimbabwe.png',
                'name' => 'Zimbabwe',
                'alpha_two_code' => 'ZW',
                'phone_code' => '+263',
            ],
        ];

        Country::insert($countries);
    }
}
