<label for='code'>Channel Code</label>
<select class="form-control1" wire:model.defer='selected_channel.channel_code' id="code">
    <option value=""> Select Code </option>
    <option value="AAT">AAT - AA Travel</option>
    <option value="ABB">ABB - Airbnb</option>
    <option value="ABR">ABR - Abreu Online</option>
    <option value="ACO">ACO - Acomodeo</option>
    <option value="AET">AET - American Express Travel (Expedia)</option>
    <option value="AGO">AGO - Agoda</option>
    <option value="AGU">AGU - Accommodation Guru</option>
    <option value="AGY">AGY - Argenway</option>
    <option value="AHC">AHC - Amex The Hotel Collection (Expedia)</option>
    <option value="AHR">AHR - Amex FINE HOTELS AND RESORTS (Expedia)</option>
    <option value="ALO">ALO - Allocate</option>
    <option value="ALT">ALT - Alturabeds</option>
    <option value="ALM">ALM - Almundo</option>
    <option value="AMD">AMD - AMADEUS</option>
    <option value="ANA">ANA - Andalucia Autentica</option>
    <option value="ANZ">ANZ - ANZCRO</option>
    <option value="AOS">AOS - Asian Overland Services</option>
    <option value="AOT">AOT - AOT Sunlover</option>
    <option value="APL">APL - Atrapalo</option>
    <option value="APT">APT - Apartool</option>
    <option value="ARC">ARC - HotelCompany/Alpharooms</option>
    <option value="ARO">ARO - AroSuite</option>
    <option value="ATE">ATE - ATEL HOTELS</option>
    <option value="ATG">ATG - AIC Travel Group</option>
    <option value="AUR">AUR - Aura.Travel</option>
    <option value="AVV">AVV - Avvio</option>
    <option value="BAH">BAH - British Airways Holidays</option>
    <option value="BAR">BAR - Barcelo Viajes</option>
    <option value="BBN">BBN - BookingButton</option>
    <option value="BBP">BBP - BookingButton Plus</option>
    <option value="BBS">BBS - BookingButton Sapphire</option>
    <option value="BCC">BCC - Bookerclub.com</option>
    <option value="BDC">BDC - Booking.com</option>
    <option value="BET">BET - Bonotel Exclusive Travel</option>
    <option value="BFT">BFT - Buffalo Tours</option>
    <option value="BHG">BHG - Bali Hotel Guide</option>
    <option value="BHO">BHO - Best Hotel Online</option>
    <option value="BIC">BIC - Bookit.com</option>
    <option value="BID">BID - Bidroom</option>
    <option value="BIW">BIW - Book It With</option>
    <option value="BKC">BKC - BookingCore</option>
    <option value="BKE">BKE - Book Easy</option>
    <option value="BKS">BKS - Bookassist</option>
    <option value="BKT">BKT - Bookit.co.nz</option>
    <option value="BLK">BLK - Bookings.lk</option>
    <option value="BOK">BOK - BookVisit | Citybreak | Nozio</option>
    <option value="BON">BON - Bookonlinenow</option>
    <option value="BRD">BRD - BridgeStreet</option>
    <option value="BST">BST - BestDay Travel</option>
    <option value="BTD">BTD - Book Today</option>
    <option value="BTH">BTH - Booking2Hotels</option>
    <option value="BTP">BTP - Book That Place</option>
    <option value="BUD">BUD - budgetplaces.com</option>
    <option value="BWE">BWE - bedswithease</option>
    <option value="BWS">BWS - Best Western CRSConnect</option>
    <option value="BWZ">BWZ - BookingWhizz</option>
    <option value="CAE">CAE - Caesar Data</option>
    <option value="CBE">CBE - BookingEngine</option>
    <option value="CBS">CBS - CBS Travel Asia</option>
    <option value="CCK">CCK - CHECK24</option>
    <option value="CCT">CCT - BookingButton Cradle Coast Tourism</option>
    <option value="CDE">CDE - Connected Destination</option>
    <option value="CDT">CDT - Condor Travel</option>
    <option value="CGO">CGO - Cangooroo</option>
    <option value="CHC">CHC - Chic Retreats</option>
    <option value="CHM">CHM - Charming Italy</option>
    <option value="CHO">CHO - Choice CRS</option>
    <option value="CHT">CHT - CheapTickets (Expedia)</option>
    <option value="CIS">CIS - Cisalpina Tours</option>
    <option value="CLD">CLD - CloudHotelier</option>
    <option value="CNS">CNS - CanadaStays</option>
    <option value="CNT">CNT - CNTravel</option>
    <option value="CSV">CSV - Clearing Station (Vioma)</option>
    <option value="CTG">CTG - CNBooking.net</option>
    <option value="CTP">CTP - Ctrip</option>
    <option value="CTZ">CTZ - CultBooking</option>
    <option value="CWT">CWT - RoomIt by CWT</option>
    <option value="CYO">CYO - Calypso</option>
    <option value="CZB">CZB - Cityzenbooking</option>
    <option value="DBH">DBH - DayBreakHotels</option>
    <option value="DDC">DDC - Despegar</option>
    <option value="DIC">DIC - Discover Australia Contract</option>
    <option value="DID">DID - Dida Travel Technology</option>
    <option value="DIP">DIP - Discover Australia Package</option>
    <option value="DIS">DIS - Discover Australia</option>
    <option value="DJO">DJO - Djoca Travel</option>
    <option value="DOW">DOW - Destinations of the World</option>
    <option value="DRI">DRI - Darmawisata Indonesia</option>
    <option value="DRM">DRM - Dorms.com</option>
    <option value="DRS">DRS - DIRS21</option>
    <option value="DSC">DSC - Destination.cool</option>
    <option value="DST">DST - Destinia S.L.</option>
    <option value="DWH">DWH - DirectWithHotels</option>
    <option value="EAN">EAN - Expedia Affiliate Network (Expedia)</option>
    <option value="EBK">EBK - EasyBookings</option>
    <option value="EBS">EBS - ebookers (Expedia)</option>
    <option value="EBW">EBW - Easybooking by Webconnection</option>
    <option value="ECL">ECL - EC Travel</option>
    <option value="ECT">ECT - ECCO Tours</option>
    <option value="EDH">EDH - eDream Hotels</option>
    <option value="EDR">EDR - ODIGEO Connect</option>
    <option value="EET">EET - Egypt Express Travel</option>
    <option value="EGD">EGD - Engrande/BudgetPlaces</option>
    <option value="EGN">EGN - Egencia (Expedia)</option>
    <option value="ELH">ELH - Exclusively Hotels (Total Stay)</option>
    <option value="ELO">ELO - eLong</option>
    <option value="EMA">EMA - BookingEye (eMarketingEye)</option>
    <option value="ENT">ENT - My Bookings / Entertainment</option>
    <option value="ESQ">ESQ - Esquiades</option>
    <option value="ETB">ETB - EasyToBook</option>
    <option value="ETL">ETL - EasyTravel</option>
    <option value="ETO">ETO - eTourism</option>
    <option value="ETS">ETS - Etstur</option>
    <option value="EUP">EUP - Europlayas NEW</option>
    <option value="EVG">EVG - Evasion Voyage</option>
    <option value="EVO">EVO - EvoSuite</option>
    <option value="EXH">EXH - Excite Holidays</option>
    <option value="EXP">EXP - Expedia</option>
    <option value="EZT">EZT - eztravel</option>
    <option value="FBK">FBK - Fastbooking</option>
    <option value="FCH">FCH - fincahotels.com</option>
    <option value="FER">FER - feratel Deskline</option>
    <option value="FHO">FHO - Fusion Holidays</option>
    <option value="FIJ">FIJ - Fiji Airways Holidays (Trisept Solutions)</option>
    <option value="FLG">FLG - Fliggy</option>
    <option value="FPH">FPH - FastPayHotels</option>
    <option value="FSH">FSH - Fishing.cool</option>
    <option value="GAM">GAM - Getaroom.com</option>
    <option value="GBB">GBB - Goibibo</option>
    <option value="GBG">GBG - Garbage</option>
    <option value="GBR">GBR - grabrooms</option>
    <option value="GCB">GCB - Golden Chain Australia</option>
    <option value="GCC">GCC - GuestCentric Systems</option>
    <option value="GCR">GCR - GuestCentric Rewards</option>
    <option value="BCS">GCS - GuestCentric Channels</option>
    <option value="GDT">GDT - GoldenTour/Koedia</option>
    <option value="GEN">GEN - GDS by SiteMinder</option>
    <option value="GHA">GHA - Google Hotel Ads (through Channex.io)</option>
    <option value="GHE">GHE - GHE (Grand Hotel Excelsior)</option>
    <option value="GHS">GHS - GoHostels.com</option>
    <option value="GIC">GIC - Guest Incoming</option>
    <option value="GIM">GIM - GIMH S.A</option>
    <option value="GLK">GLK - Guestlink</option>
    <option value="GLL">GLL - GALILEO</option>
    <option value="GMO">GMO - Gomio</option>
    <option value="GMT">GMT - GOMMT</option>
    <option value="GNA">GNA - GNA Hotel Solutions</option>
    <option value="GNC">GNC - Grand National Concierge</option>
    <option value="GOA">GOA - Go2Africa</option>
    <option value="GOT">GOT - Grupo Opentours</option>
    <option value="GOW">GOW - Gowaii</option>
    <option value="GQO">GQO - GoQuo</option>
    <option value="GTA">GTA - GTA-Travel</option>
    <option value="HAB">HAB - Habicus Group (SilverDoor)</option>
    <option value="HAN">HAN - Hana Tour</option>
    <option value="HAO">HAO - Haoqiao</option>
    <option value="HBD">HBD - Hotelbeds</option>
    <option value="HBN">HBN - HBN Online</option>
    <option value="HBZ">HBZ - Hotel Bonanza</option>
    <option value="HCC">HCC - Hardin County Conservation</option>
    <option value="HCL">HCL - HotelsClick</option>
    <option value="HCO">HCO - HotelsCombined</option>
    <option value="HDT">HDT - Hotel Direct</option>
    <option value="HEX">HEX - HotelExchange</option>
    <option value="HGO">HGO - Hutchgo</option>
    <option value="HIH">HIH - HiHostels</option>
    <option value="HIP">HIP - HipInn.com</option>
    <option value="HIS">HIS - HotelsInOne</option>
    <option value="HJZ">HJZ - Hoojoozat</option>
    <option value="HKC">HKC - Hong Kong Convergent</option>
    <option value="HLB">HLB - HalalBooking</option>
    <option value="HLP">HLP - HotelsPro</option>
    <option value="HLS">HLS - Hoteliers.com</option>
    <option value="HNL">HNL - Hotels.nl</option>
    <option value="HNS">HNS - HotelNetSolutions</option>
    <option value="HNT">HNT - Realtime Travel Solutions</option>
    <option value="HOO">HOO - HotelOnline</option>
    <option value="HOS">HOS - HotelSpecials.nl</option>
    <option value="HPO">HPO - HotelPro IBE</option>
    <option value="HQK">HQK - HotelQuickly</option>
    <option value="HRA">HRA - H-Résa (MisterFly)</option>
    <option value="HRE">HRE - HReservations (BookitNow)</option>
    <option value="HRS">HRS - HRS - Hotel Reservation Service</option>
    <option value="HRS">HRS - Hrs.com</option>
    <option value="HRT">HRT - Hero Travel</option>
    <option value="HSC">HSC - HostelsClub</option>
    <option value="HSP">HSP - HotelShopuk</option>
    <option value="HST">HST - HS Travel</option>
    <option value="HSU">HSU - HotelShopuk - NEW (to replace the above soon)</option>
    <option value="HTC">HTC - HostelCulture</option>
    <option value="HTD">HTD - hotelthailland</option>
    <option value="HTI">HTI - HTI/eRes</option>
    <option value="HTL">HTL - Hotels.com (Expedia)</option>
    <option value="HTM">HTM - Hotelerum</option>
    <option value="HTN">HTN - HotelTonight</option>
    <option value="HTP">HTP - Hoterip</option>
    <option value="HTR">HTR - HotelTravel</option>
    <option value="HTS">HTS - HotelTools</option>
    <option value="HTT">HTT - Hotetec</option>
    <option value="HTV">HTV - Hotels.tv</option>
    <option value="HUA">HUA - Hua Min Tourism Reservation</option>
    <option value="HUN">HUN - Hunting.cool</option>
    <option value="HUS">HUS - Hotusa</option>
    <option value="HUT">HUT - Hutchgo.com</option>
    <option value="HWL">HWL - Hostel World</option>
    <option value="HWL">HWL - HostelBookers (HostelWorld Group)</option>
    <option value="HWR">HWR - Hotwire (Expedia)</option>
    <option value="HYM">HYM - HotelPartner YM</option>
    <option value="IBC">IBC - IBC Hotels</option>
    <option value="IBK">IBK - GHS iBooking</option>
    <option value="ICI">ICI - iCastelli</option>
    <option value="IDO">IDO - Idiso</option>
    <option value="IES">IES - i-escape</option>
    <option value="IHL">IHL - iHotelier</option>
    <option value="IHW">IHW - iHotelier PMSConnect</option>
    <option value="IMP">IMP - ImperaTours</option>
    <option value="INF">INF - Infinite Hotel</option>
    <option value="INS">INS - Instant Bookings (e-Travel Marketing)</option>
    <option value="INZ">INZ - Innstant (Zenith)</option>
    <option value="IOS">IOS - In1Solutions</option>
    <option value="ITL">ITL - Inovtravel</option>
    <option value="ITP">ITP - Inntopia</option>
    <option value="JAC">JAC - JacTravel</option>
    <option value="JET">JET - Jetstar/Hooroo/Qantas</option>
    <option value="JMB">JMB - Jumbo Tours</option>
    <option value="JMI">JMI - Jumia Travel</option>
    <option value="JTB">JTB - JTB Hawaii</option>
    <option value="JTG">JTG - JTB Group</option>
    <option value="JTH">JTH - Jet2holidays</option>
    <option value="KRL">KRL - KiwiRail</option>
    <option value="KRZ">KRZ - Kurzurlaub</option>
    <option value="KTL">KTL - Keytel</option>
    <option value="LDO">LDO - Lido</option>
    <option value="LMA">LMA - Lastminute.au (Expedia)</option>
    <option value="LNA">LNA - Lusanova</option>
    <option value="LOH">LOH - Lots Of Hotels</option>
    <option value="LOV">LOV - loveholidays</option>
    <option value="LRM">LRM - LateRooms/AsiaRooms</option>
    <option value="LRW">LRW - LateRooms</option>
    <option value="LRW">LRW - LateRooms/AsiaRooms LRConnect</option>
    <option value="LSC">LSC - LeisureCom</option>
    <option value="LUX">LUX - LUXOS Select</option>
    <option value="LVN">LVN - LivnTravel</option>
    <option value="LXE">LXE - Luxury Escapes</option>
    <option value="LXN">LXN - Luxe Nomad</option>
    <option value="MAL">MAL - misteraladin.com</option>
    <option value="MAX">MAX - MaxEngine</option>
    <option value="MCP">MCP - EziBed/Mitchell Corp</option>
    <option value="MCW">MCW - Mitchell Corp Wholesale</option>
    <option value="MDR">MDR - Macdonald Resorts</option>
    <option value="MGC">MGC - MagicStay</option>
    <option value="MGH">MGH - MG Holiday</option>
    <option value="MGK">MGK - MG Bedbank</option>
    <option value="MGO">MGO - Migoa</option>
    <option value="MHB">MHB - MyHotelBreak</option>
    <option value="MJT">MJT - MrJet (Expedia)</option>
    <option value="MKT">MKT - Miki Travel</option>
    <option value="MMS">MMS - Mr and Mrs Smith</option>
    <option value="MPG">MPG - Meeting Point Global</option>
    <option value="MRI">MRI - Mirai</option>
    <option value="MRS">MRS - Myeres.com</option>
    <option value="MRZ">MRZ - BookingButton MyRez</option>
    <option value="MSL">MSL - Marsol</option>
    <option value="MTC">MTC - MTC Group SA</option>
    <option value="MYX">MYX - Xcaliber</option>
    <option value="NAM">NAM - NamuTravel</option>
    <option value="NAY">NAY - NetAffinity</option>
    <option value="NBE">NBE - NewBook Express</option>
    <option value="NBK">NBK - NeoBookings</option>
    <option value="NEC">NEC - Neckermann (Expedia)</option>
    <option value="NIN">NIN - NeedItNow</option>
    <option value="NIV">NIV - Niu Viatge</option>
    <option value="NOM">NOM - Nomads and Base</option>
    <option value="NON">NON - Not 1 Night</option>
    <option value="NTN">NTN - NT Incoming</option>
    <option value="NTT">NTT - Nites Travel</option>
    <option value="NXT">NXT - Nextel.travel</option>
    <option value="OBK">OBK - Rusticae</option>
    <option value="OHR">OHR - 1HotelRez</option>
    <option value="OLV">OLV - Olympia Viaggi</option>
    <option value="OME">OME - Omega Hotels</option>
    <option value="ONE">ONE - OneNight</option>
    <option value="OPL">OPL - Off Peak Luxury</option>
    <option value="ORZ">ORZ - Orbitz (Expedia)</option>
    <option value="OTB">OTB - On The Beach</option>
    <option value="OTS">OTS - Open Travel Service</option>
    <option value="OSA">OSA - Insatnt Booking Page</option>
    <option value="OTZ">OTZ - otelz.com</option>
    <option value="OVK">OVK - Ostrovok</option>
    <option value="OZA">OZA - OzAccom</option>
    <option value="PBB">PBB - Pacific BedBank</option>
    <option value="PCH">PCH - Priceline Hong Kong</option>
    <option value="PCL">PCL - Priceline.com</option>
    <option value="PGI">PGI - PegiPegi</option>
    <option value="PMR">PMR - Portimar</option>
    <option value="PPN">PPN - Pan Pacific Travel</option>
    <option value="PRF">PRF - Profitroom</option>
    <option value="PSC">PSC - Emviagem</option>
    <option value="PTA">PTA - Prestigia</option>
    <option value="PTC">PTC - PTC Express Travel</option>
    <option value="PTH">PTH - Paraty Hotels</option>
    <option value="PTL">PTL - PriceTravel</option>
    <option value="PYJ">PYJ - PetsPyjamas</option>
    <option value="QBD">QBD - Flight Centre Travel Group</option>
    <option value="QRS">QRS - Quantum Reservations</option>
    <option value="RAK">RAK - Rakuten</option>
    <option value="RAL">RAL - ResortsandLodges.com</option>
    <option value="RAT">RAT - Openhotelier (ex. RoomAllot)</option>
    <option value="RCK">RCK - ResClick</option>
    <option value="RCL">RCL - Reconline</option>
    <option value="RFA">RFA - Roamfree</option>
    <option value="RGL">RGL - Regal</option>
    <option value="RKR">RKR - RajaKamar</option>
    <option value="RLG">RLG - ResLogic</option>
    <option value="RML">RML - Roomlia</option>
    <option value="ROI">ROI - Roiback</option>
    <option value="ROM">ROM - Roomex</option>
    <option value="RPO">RPO - Rapibo</option>
    <option value="RSD">RSD - Reserve Direct</option>
    <option value="RST">RST - Resortime</option>
    <option value="RSV">RSV - Rezserve</option>
    <option value="RTD">RTD - Room-Trade</option>
    <option value="RTL">RTL - Restel</option>
    <option value="RTS">RTS - Kognitiv</option>
    <option value="RVG">RVG - RezViewNG</option>
    <option value="RVP">RVP - GuestLeader</option>
    <option value="RWD">RWD - Rewards Corp</option>
    <option value="RXM">RXM - roomsXML.com</option>
    <option value="RYR">RYR - Ryanair Rooms</option>
    <option value="RZL">RZL - RezLive.com</option>
    <option value="SAH">SAH - South African Hotels</option>
    <option value="SAN">SAN - Safarinow.com</option>
    <option value="SAW">SAW - Serviced Apartments Worldwide</option>
    <option value="SCO">SCO - ScottDunn</option>
    <option value="SDB">SDB - SpeedyBooker.com</option>
    <option value="SEC">SEC - Secretplaces</option>
    <option value="SER">SER - Serhs Tourism</option>
    <option value="SET">SET - Setours</option>
    <option value="SFH">SFH - Surfholidays.com</option>
    <option value="SHR">SHR - Stash Hotel Rewards</option>
    <option value="SIT">SIT - Sidetours</option>
    <option value="SMB">SMB - Sembo</option>
    <option value="SMP">SMP - Simple Booking</option>
    <option value="SNH">SNH - SilverNeedle Hotels</option>
    <option value="SOL">SOL - Solferias</option>
    <option value="SPB">SPB - SuperBreak</option>
    <option value="SPD">SPD - Splendia</option>
    <option value="SPI">SPI - Spies (Expedia)</option>
    <option value="SPK">SPK - SuperBreak (New)</option>
    <option value="SST">SST - Sun Series Travel</option>
    <option value="STA">STA - Stay247</option>
    <option value="STL">STL - Southall Travel</option>
    <option value="STS">STS - Staylists</option>
    <option value="STV">STV - STA Travel</option>
    <option value="STW">STW - Special Tours Wholesalers</option>
    <option value="STY">STY - Stay Today</option>
    <option value="SUN">SUN - SunHotels</option>
    <option value="SWE">SWE - Sawadee</option>
    <option value="SYX">SYX - Synxis</option>
    <option value="TAF">TAF - Thompsons Africa</option>
    <option value="TAN">TAN - TA Network</option>
    <option value="TAU">TAU - TOMAS Travel - Austria</option>
    <option value="TBE">TBE - TOMAS Travel - Berlin</option>
    <option value="TBH">TBH - TabletHotels</option>
    <option value="TBK">TBK - Travelbook.ph</option>
    <option value="TBL">TBL - TravelBullz (new)</option>
    <option value="TBO">TBO - TBOHolidays</option>
    <option value="TBZ">TBZ - TravelBullz</option>
    <option value="TCO">TCO - Tourico</option>
    <option value="TDZ">TDZ - Tour10</option>
    <option value="THN">THN - The Hotel Network</option>
    <option value="THO">THO - The Hotel Network (new)</option>
    <option value="TIB">TIB - TripConnect Instant Booking</option>
    <option value="TIK">TIK - Tikitour</option>
    <option value="TJG">TJG - Tjareborg (Expedia)</option>
    <option value="TKH">TKH - ThinkHotels</option>
    <option value="TKT">TKT - Tiket.com</option>
    <option value="TLE">TLE - Tumlare</option>
    <option value="TLO">TLO - Travelio.com</option>
    <option value="TMS">TMS - TOMAS Travel</option>
    <option value="TNU">TNU - Tuniu</option>
    <option value="TOA">TOA - Trend OperaDora</option>
    <option value="TOP">TOP - Shanghai Toptown</option>
    <option value="TPC">TPC - Trepic</option>
    <option value="TPL">TPL - Tourplan</option>
    <option value="TRA">TRA - Tripadvisor Feed Channel</option>
    <option value="TRA">TRA - Tripadvisor Vacation Rentals</option>
    <option value="TRB">TRB - TravelBird</option>
    <option value="TRC">TRC - Traveliko.com</option>
    <option value="TRG">TRG - Lastminute.com</option>
    <option value="TRG">TRG - Lastminute.com - formerly Travelocity (GHE)</option>
    <option value="TRK">TRK - Traveloka</option>
    <option value="TRL">TRL - Travelanium</option>
    <option value="TRN">TRN - Travelsens</option>
    <option value="TRP">TRP - dnata</option>
    <option value="TRP">TRP - Travel Republic</option>
    <option value="TRS">TRS - TARS</option>
    <option value="TRV">TRV - Travelocity (Expedia)</option>
    <option value="TST">TST - TravelStay</option>
    <option value="TSW">TSW - TOMAS Travel - Switzerland</option>
    <option value="TTC">TTC - The Travel Company LTD</option>
    <option value="TTH">TTH - TOMAS Travel - Thuringia</option>
    <option value="TTP">TTP - Travel Tripper</option>
    <option value="TTT">TTT - Tradewinds Tours & Travel</option>
    <option value="TTV">TTV - Trav Travel</option>
    <option value="TUN">TUN - Concorde - BookingEngine</option>
    <option value="TUR">TUR - Turu</option>
    <option value="TVC">TVC - Travco Corporation</option>
    <option value="TVS">TVS - TravelStay Network Services</option>
    <option value="TVT">TVT - Traveltool</option>
    <option value="TVY">TVY - Trust Voyager</option>
    <option value="TXA">TXA - Tourism Exchange Australia</option>
    <option value="UNR">UNR - Unister</option>
    <option value="VAC">VAC - Vacatia</option>
    <option value="VCS">VCS - VacayHome Connect</option>
    <option value="VET">VET - Veturis Travel</option>
    <option value="VII">VII - Viajes Interrias</option>
    <option value="VIN">VIN - Ving (Expedia)</option>
    <option value="VJU">VJU - Viajes Urbis</option>
    <option value="VOL">VOL - Viajes Olympia</option>
    <option value="VOO">VOO - Voordeeluitjes</option>
    <option value="VRB">VRB - Homeaway / VRBO</option>
    <option value="VRC">VRC - VeryChic</option>
    <option value="TUJ">TUJ - Tujia</option>
    <option value="WAK">WAK - Waka</option>
    <option value="WBE">WBE - WorldBlue</option>
    <option value="WBK">WBK - Wubook</option>
    <option value="WBR">WBR - WebRooms (Welman)</option>
    <option value="WDC">WDC - Wide Discovery</option>
    <option value="WHL">WHL - WHL Alba Travel</option>
    <option value="WIC">WIC - Welcome Incoming</option>
    <option value="WKD">WKD - Weekendesk</option>
    <option value="WKL">WKL - WeKnowLondon</option>
    <option value="WNP">WNP - Wanup</option>
    <option value="WOT">WOT - Wotif (Expedia)</option>
    <option value="WST">WST - Website Travel</option>
    <option value="WTA">WTA - Wel-Travel Australia</option>
    <option value="WTB">WTB - Witbooking</option>
    <option value="XAT">XAT - Leisure Connector (X-Adapt)</option>
    <option value="XNI">XNI - Xenia International</option>
    <option value="YAU">YAU - YHA Australia</option>
    <option value="YNZ">YNZ - YHA New Zealand</option>
    <option value="ZNU">ZNU - Zanadu</option>
    <option value="ZOO">ZOO - Travelzoo</option>
    <option value="ZUM">ZUM - Zumata</option>
</select>
